### PR TITLE
Feature flag: Optional public networking only

### PR DESCRIPTION
**Pull request by morganrowse**
Understandable you are not accepting contribution at this point, please find attached PR for when you decide to save your customers cost regarding natgw.

feat: add opt-in feature flag `aft_feature_disable_private_networking` to disable private networking infrastructure

- run lambdas outside of vpc
- run codebuild outside of vpc
- run codestar outside of vpc
- remove natgw and private subnets
- sparse formatting

# Contributing to the AWS Control Tower Account Factory for Terraform

Thank you for your interest in contributing to the AWS Control Tower Account Factory for Terraform.

At this time, we are not accepting contributions. If contributions are accepted in the future, the AWS Control Tower Account Factory for Terraform is released under the [Apache license](http://aws.amazon.com/apache2.0/) and any code submitted will be released under that license.

If you have a feature request, please create an issue using the Feature Request template, thanks!

### CODE REVIEW

**Comment by hanafya** [comment]
Thanks for the pull request! We’re not accepting contributions at this time, but we’ll add this to our feature request backlog.

**Comment by brakf** [comment]
Dear @hanafya, 
what is the status of the backlog item? From what I read in the issue's many customers are looking for the same and using this PR would be a fast and easy solution.

**Comment by thebigcosinus** [comment]
Do you have an update for this feature ?

**Comment by FidelusAleksander** [comment]
@aws-ia-ci @andrew-glenn @hanafya 

Anyone has an update on this new parameter?

**Pull request closed without merging**
